### ISSUE TITLE
Why mac only?

### ISSUE THREAD

**Issue by tsi** [tholman/overscroll#3]
Could you please explain what makes the code limited to macs only? I have a client that needs something similar and I'd really like to have a go at making it [cross-universe compatible](http://html9responsiveboilerstrapjs.com/) :)

**Comment by Martin-Pitt** [comment]
The reason is because overscroll is a native Mac OSX functionality (Every single scrollable pane has it, to the point of overuse).

I guess for keeping the library simple.
Also you don't want to start overriding/messing with the users native scrolling mechanism as that can have significant usability/accessibility repercussions.

(E.g. I like to use the middle-mouse scroll widget on my windows machine at home to read articles slowly, but my experience is destroyed when the site kills my scrolling capabilities by using iScroll, ugh)

**Comment by tsi** [comment]
I see, I tried toady to mimic this behavior but I realized that once I got to the end of the document the scroll event won't fire anymore, even if I tried to scroll further. bummer.
I guess we can mark it as 'won't be fixed' :)
Thanks!

**Comment by tholman** [comment]
Yeah, definitely a wontfix :(

Thanks for closing :D
