### ISSUE TITLE
Live demo does not work

### ISSUE THREAD

**Issue by jasekiw** [tholman/overscroll#7]
I've tested In Edge, Chrome, Firefox, and Safari and the live demo does not work on any of them on Desktop. It does however work on an iphone in safari. If this does not work on OSX anymore then it should be stated so on the readme and on the demo page.

http://tholman.com/overscroll/

**Comment by byman64** [comment]
Confirmed, same here with Chrome 85 nothig happening

**Comment by tholman** [comment]
Sadly browsers have continued to change how they report the bouncy scroll at the end of pages... were left with iOS chrome and safari currently I believe.

**Comment by byman64** [comment]
I see,thanks  QooL SpiritAntonino Migliore  Da: Tim HolmanInviato: domenica 20 settembre 2020 14:26A: tholman/overscrollCc: byman64; CommentOggetto: Re: [tholman/overscroll] Live demo does not work (#7) Sadly browsers have continued to change how they report the bouncy scroll at the end of pages... were left with iOS chrome and safari currently I believe.—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by tholman** [comment]
The browsers have since patched this quirk, ios is still working which i've updated the description to say. cant win em all really
